Add optional config parameter to adjust the page_size
singer-io/tap-surveymonkey pull request #9
Opened 2020-03-04 14:21 UTC by abij

# Description of change

I'm running into a limit of nr-api-calls per day, so a small optimization is to use a 100-items per_page fetching.

I have added the config param fetch_per_page which is passed as the per_page paramater in http-request. This allows larger page-sizes and less API-calls.

# QA steps
 - [ ] automated tests passing
 - [ ] manual qa steps passing (list below)

# Risks

# Rollback steps
 - revert this branch

2020-03-04 14:21 UTC, cmerrick commented
Hi @abij, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

2020-03-05 10:03 UTC, cmerrick commented
You did it @abij!

Thank you for signing the Singer Contribution License Agreement.

2020-03-19 17:22 UTC, KAllan357 requested changes

2020-03-19 17:22 UTC, KAllan357 commented on sample_config.json
> +  "fetch_per_page": "50"
Could you rename this throughout to `page_size`?

2020-03-20 14:29 UTC, KAllan357 approved these changes

2020-03-20 14:30 UTC, merged